### ISSUE TITLE
Templates and pages is missed

### ISSUE THREAD

**Issue by fardad-dev** [Dan503/gulp-auto-imports#19]
Atomic design structure has template and pages which missed.

**Comment by Dan503** [comment]
Can you provide more details?

There isn't enough information here for me to help you.

What are you passing into gulp-auto-imports?
What does your folder structure look like?
Have you tried using the `createAutoImportTask` function?

**Comment by fardad-dev** [comment]
My atomic design structure is
- atoms
- molecules
- organisms
- templates
- pages

**Comment by fardad-dev** [comment]
I created a test for atomic design
https://github.com/hosseinmd/reactjs-view/blob/master/src/tests/src/atomicStructure.ts
This code testing components to don't import incorrect or don't be in incorrect place, for example: atoms shouldn't import molecules

**Comment by fardad-dev** [comment]
> Have you tried using the createAutoImportTask function?

What does this do?

**Comment by Dan503** [comment]
I had a look at your repo
https://github.com/hosseinmd/reactjs-view

I can't see any sign of a gulp workflow in that project.

This is a Gulp plugin (https://gulpjs.com/)

You need to set up a gulp build pipeline for this plugin to be able to do anything.

**Comment by Dan503** [comment]
> > Have you tried using the createAutoImportTask function?
>
> What does this do?

It is a function that produces auto-import Gulp tasks more easily. [See the documentation](https://github.com/Dan503/gulp-auto-imports#using-the-automated-gulp-task-generator-function) for details on how to use it.
